# -*- coding: utf-8 -*-
"""Program2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyD1AqguIRkh8gvxQnIAE9mke0OyKBOO

Matrix Operations
"""

import numpy as np
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[9,8,7],[6,5,4],[3,2,1]])
matrix_sum=matrix1 + matrix2
matrix_diff=matrix1 - matrix2
matrix_product=matrix1*matrix2
matrix_divide=matrix1 / matrix2
matrix_multiply=np.dot(matrix1,matrix2)
matrix1_transpose=np.transpose(matrix1)
diagonal_sum=np.trace(matrix1)
print("Matrix 1:\n",matrix1)
print("Matrix 2:\n",matrix2)
print("Sum:\n",matrix_sum)
print("Difference:\n",matrix_diff)
print("Product:\n",matrix_product)
print("Division:\n",matrix_divide)
print("Multiplication:\n",matrix_multiply)
print("Transpose of Matrix 1:\n",matrix1_transpose)
print("Sum of diagonal elements of matrix 1:",diagonal_sum)